import * as React from 'react';
import type { AuraOddsMarketType } from '@/lib/aura/odds-strip-types';
import type { AuraGameMarketBoardModel, AuraGameMarketBoardState, AuraGameMarketTeam } from '@/lib/aura/game-market-board-types';
import './game-market-board.css';
export function AuraGameMarketBoard({ state, onMarketChange, className = '' }: { state: AuraGameMarketBoardState; onMarketChange?: (market: AuraOddsMarketType) => void; className?: string }) { return state.model ? <AuraGameMarketBoardView model={state.model} onMarketChange={onMarketChange} className={className} /> : <section className={`aura-game-markets ${className}`}><p className="aura-game-markets__empty">{state.error || 'Market unavailable.'}</p></section>; }
export function AuraGameMarketBoardView({ model, onMarketChange, className = '' }: { model: AuraGameMarketBoardModel; onMarketChange?: (market: AuraOddsMarketType) => void; className?: string }) { return <section className={`aura-game-markets ${className}`.trim()}><header><small>{model.game.league}</small><span>{model.game.status}</span></header><div className="aura-game-markets__matchup"><Team team={model.game.away}/><i>at</i><Team team={model.game.home}/></div><nav aria-label="Market type">{model.availableMarkets.map((market) => <button key={market} type="button" aria-pressed={market === model.market.marketType} onClick={() => onMarketChange?.(market)}>{label(market)}</button>)}</nav><div className="aura-game-markets__prices">{model.market.outcomes.map((outcome) => <button type="button" key={outcome.side}><span>{outcome.label}</span><strong>{outcome.line === null ? format(outcome.price) : format(outcome.line)}</strong><small>{outcome.line === null ? 'Moneyline' : format(outcome.price)}</small></button>)}</div><footer><span>Current retained market</span><time>{model.market.asOf ? new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(model.market.asOf) : 'Unavailable'}</time></footer></section>; }
function Team({ team }: { team: AuraGameMarketTeam }) { return <div><span style={{ background: team.color }}>{team.abbreviation.slice(0, 1)}</span><strong>{team.abbreviation}</strong><small>{team.name}</small><b>{team.score ?? '—'}</b></div>; }
function label(value: AuraOddsMarketType) { return value === 'moneyline' ? 'Moneyline' : value === 'spread' ? 'Spread' : 'Total'; }
function format(value: number | null) { return value === null ? '—' : value > 0 ? `+${value}` : String(value); }
