// Real retained production data, captured verbatim on 2026-08-14 (UTC).
// Source: GET https://aura.tl/api/showcase/research-landscape (production league-landscape result, verbatim).
// Cohort: 2026 MLB player batting landscape — at bats vs batting average, 36 returned entities.
// Never fabricate fixture data — recapture from a real board instead.
import { toAuraLeagueLandscape, type AuraLeagueLandscape } from '@/lib/aura/league-analytics-types';

export const auraLeagueAnalyticsFixture: AuraLeagueLandscape = toAuraLeagueLandscape({
  "contractVersion": "2.0.0",
  "kind": "aura.research.league-landscape",
  "availability": {
    "state": "available",
    "reason": null
  },
  "generatedAt": 1786676223345,
  "entityType": "player",
  "axes": {
    "x": {
      "definitionId": "baseball.player.at_bats",
      "label": "At bats",
      "unit": {
        "kind": "count"
      },
      "directionality": "higher_better",
      "dimensions": {
        "window": "game"
      }
    },
    "y": {
      "definitionId": "baseball.player.batting_average",
      "label": "Batting average",
      "unit": {
        "kind": "ratio"
      },
      "directionality": "higher_better",
      "dimensions": {
        "window": "season_to_date"
      }
    },
    "size": {
      "definitionId": "baseball.player.hits",
      "label": "Hits",
      "unit": {
        "kind": "count"
      },
      "directionality": "higher_better",
      "dimensions": {
        "window": "game"
      }
    },
    "color": {
      "definitionId": "baseball.player.runs",
      "label": "Runs",
      "unit": {
        "kind": "count"
      },
      "directionality": "higher_better",
      "dimensions": {
        "window": "game"
      }
    },
    "outcome": {
      "definitionId": "baseball.player.runs",
      "label": "Runs",
      "unit": {
        "kind": "count"
      },
      "directionality": "higher_better",
      "dimensions": {
        "window": "game"
      }
    }
  },
  "sample": {
    "games": 64,
    "completeEntities": 397,
    "returnedEntities": 36,
    "aggregation": "latest",
    "phases": []
  },
  "domains": {
    "x": [
      0,
      6
    ],
    "y": [
      0,
      1
    ],
    "size": [
      0,
      3
    ],
    "color": [
      0,
      4
    ]
  },
  "quadrants": {
    "method": "Median split within the complete filtered cohort.",
    "xSplit": 3,
    "ySplit": 0.244
  },
  "frontier": {
    "method": "Non-dominated Pareto frontier using explicit axis directionality."
  },
  "targetBand": {
    "available": true,
    "method": "Interquartile x/y rectangle among successful entities in the complete filtered cohort.",
    "outcome": {
      "definitionId": "baseball.player.runs",
      "operator": "gte",
      "threshold": 1,
      "label": "Scored in the latest retained game"
    },
    "successfulEntities": 107,
    "bounds": {
      "xMin": 3,
      "xMax": 4,
      "yMin": 0.2285,
      "yMax": 0.2705
    },
    "coverage": 0.3645,
    "precision": 0.3362,
    "reason": null
  },
  "points": [
    {
      "id": "mlb:multi_source:player:5194635",
      "name": "Abimelec Ortiz",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.333,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.9899
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": true
    },
    {
      "id": "mlb:multi_source:player:5133392",
      "name": "Eduardo Valencia",
      "team": null,
      "position": null,
      "x": 3,
      "y": 0.386,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.5025,
        "y": 0.9949
      },
      "quadrant": "high-high",
      "cluster": "cluster-2",
      "frontier": true
    },
    {
      "id": "mlb:multi_source:player:4683391",
      "name": "Victor Mederos",
      "team": null,
      "position": null,
      "x": 0,
      "y": 1,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.0442,
        "y": 1
      },
      "quadrant": "low-high",
      "cluster": "cluster-1",
      "frontier": true
    },
    {
      "id": "mlb:multi_source:player:39572",
      "name": "Luis Arraez",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.316,
      "size": 3,
      "color": 0,
      "successful": false,
      "percentile": {
        "x": 0.9545,
        "y": 0.9798
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": true
    },
    {
      "id": "mlb:multi_source:player:4912412",
      "name": "Ronny Simon",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.333,
      "size": 2,
      "color": 0,
      "successful": false,
      "percentile": {
        "x": 0.774,
        "y": 0.9899
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": true
    },
    {
      "id": "mlb:multi_source:player:4228472",
      "name": "Spencer Horwitz",
      "team": null,
      "position": null,
      "x": 6,
      "y": 0.262,
      "size": 2,
      "color": 0,
      "successful": false,
      "percentile": {
        "x": 0.9975,
        "y": 0.7008
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": true
    },
    {
      "id": "mlb:multi_source:player:33481",
      "name": "Yandy Diaz",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.302,
      "size": 2,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.9545
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4725251",
      "name": "Liam Hicks",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.284,
      "size": 3,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.8914
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:5207167",
      "name": "Sam Antonacci",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.28,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.8649
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4905921",
      "name": "Junior Caminero",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.279,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.8535
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:5005912",
      "name": "Jonny DeLuca",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.273,
      "size": 3,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.8207
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4311634",
      "name": "Nick Gonzales",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.309,
      "size": 2,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.9697
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:42664",
      "name": "Jake Mangum",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.301,
      "size": 3,
      "color": 3,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.952
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4987382",
      "name": "Ceddanne Rafaela",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.288,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.9167
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:5149072",
      "name": "Kevin McGonigle",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.286,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.9078
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:40810",
      "name": "Jonathan Aranda",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.285,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.9003
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:42402",
      "name": "CJ Abrams",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.284,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.8914
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4414531",
      "name": "Zack Gelof",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.28,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.8649
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:36181",
      "name": "Mickey Moniak",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.271,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.8081
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:5007615",
      "name": "Caleb Durbin",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.253,
      "size": 3,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.6187
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4917694",
      "name": "Elly De La Cruz",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.268,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.7778
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4926296",
      "name": "Jac Caglianone",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.268,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.7778
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:5137200",
      "name": "Esmerlyn Valdez",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.25,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.577
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:33712",
      "name": "Kyle Schwarber",
      "team": null,
      "position": null,
      "x": 5,
      "y": 0.25,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.9545,
        "y": 0.577
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:41355",
      "name": "Geraldo Perdomo",
      "team": null,
      "position": null,
      "x": 6,
      "y": 0.245,
      "size": 2,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.9975,
        "y": 0.5189
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4717903",
      "name": "Zac Veen",
      "team": null,
      "position": null,
      "x": 3,
      "y": 0.333,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.5025,
        "y": 0.9899
      },
      "quadrant": "high-high",
      "cluster": "cluster-2",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:38904",
      "name": "Bo Bichette",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.262,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.7008
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4345070",
      "name": "Alec Burleson",
      "team": null,
      "position": null,
      "x": 3,
      "y": 0.287,
      "size": 2,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.5025,
        "y": 0.9129
      },
      "quadrant": "high-high",
      "cluster": "cluster-2",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:32127",
      "name": "Javier Baez",
      "team": null,
      "position": null,
      "x": 3,
      "y": 0.285,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.5025,
        "y": 0.9003
      },
      "quadrant": "high-high",
      "cluster": "cluster-2",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:39706",
      "name": "Isaac Paredes",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.254,
      "size": 0,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.6275
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4684778",
      "name": "Jordan Walker",
      "team": null,
      "position": null,
      "x": 3,
      "y": 0.284,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.5025,
        "y": 0.8914
      },
      "quadrant": "high-high",
      "cluster": "cluster-2",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:30951",
      "name": "Bryce Harper",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.253,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.6187
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:37232",
      "name": "Donovan Walton",
      "team": null,
      "position": null,
      "x": 3,
      "y": 0.282,
      "size": 1,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.5025,
        "y": 0.8826
      },
      "quadrant": "high-high",
      "cluster": "cluster-2",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:5136929",
      "name": "Chase Meidroth",
      "team": null,
      "position": null,
      "x": 3,
      "y": 0.279,
      "size": 2,
      "color": 2,
      "successful": true,
      "percentile": {
        "x": 0.5025,
        "y": 0.8535
      },
      "quadrant": "high-high",
      "cluster": "cluster-2",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:42933",
      "name": "Jared Triolo",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.25,
      "size": 3,
      "color": 3,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.577
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    },
    {
      "id": "mlb:multi_source:player:4917889",
      "name": "Daylen Lile",
      "team": null,
      "position": null,
      "x": 4,
      "y": 0.249,
      "size": 2,
      "color": 1,
      "successful": true,
      "percentile": {
        "x": 0.774,
        "y": 0.5568
      },
      "quadrant": "high-high",
      "cluster": "cluster-3",
      "frontier": false
    }
  ],
  "modelReady": {
    "format": "aura.landscape.records.v1",
    "columns": [
      "entityId",
      "name",
      "team",
      "position",
      "x",
      "y",
      "size",
      "color",
      "outcome",
      "successful",
      "xSamples",
      "ySamples",
      "xPercentile",
      "yPercentile",
      "quadrant",
      "cluster",
      "frontier"
    ],
    "rows": [
      [
        "mlb:multi_source:player:5194635",
        "Abimelec Ortiz",
        null,
        null,
        4,
        0.333,
        2,
        2,
        2,
        true,
        3,
        3,
        0.774,
        0.9899,
        "high-high",
        "cluster-3",
        true
      ],
      [
        "mlb:multi_source:player:5133392",
        "Eduardo Valencia",
        null,
        null,
        3,
        0.386,
        1,
        1,
        1,
        true,
        3,
        3,
        0.5025,
        0.9949,
        "high-high",
        "cluster-2",
        true
      ],
      [
        "mlb:multi_source:player:4683391",
        "Victor Mederos",
        null,
        null,
        0,
        1,
        1,
        1,
        1,
        true,
        1,
        1,
        0.0442,
        1,
        "low-high",
        "cluster-1",
        true
      ],
      [
        "mlb:multi_source:player:39572",
        "Luis Arraez",
        null,
        null,
        5,
        0.316,
        3,
        0,
        0,
        false,
        5,
        5,
        0.9545,
        0.9798,
        "high-high",
        "cluster-3",
        true
      ],
      [
        "mlb:multi_source:player:4912412",
        "Ronny Simon",
        null,
        null,
        4,
        0.333,
        2,
        0,
        0,
        false,
        3,
        3,
        0.774,
        0.9899,
        "high-high",
        "cluster-3",
        true
      ],
      [
        "mlb:multi_source:player:4228472",
        "Spencer Horwitz",
        null,
        null,
        6,
        0.262,
        2,
        0,
        0,
        false,
        3,
        3,
        0.9975,
        0.7008,
        "high-high",
        "cluster-3",
        true
      ],
      [
        "mlb:multi_source:player:33481",
        "Yandy Diaz",
        null,
        null,
        5,
        0.302,
        2,
        1,
        1,
        true,
        4,
        4,
        0.9545,
        0.9545,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4725251",
        "Liam Hicks",
        null,
        null,
        5,
        0.284,
        3,
        1,
        1,
        true,
        4,
        4,
        0.9545,
        0.8914,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:5207167",
        "Sam Antonacci",
        null,
        null,
        5,
        0.28,
        2,
        2,
        2,
        true,
        4,
        4,
        0.9545,
        0.8649,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4905921",
        "Junior Caminero",
        null,
        null,
        5,
        0.279,
        2,
        2,
        2,
        true,
        4,
        4,
        0.9545,
        0.8535,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:5005912",
        "Jonny DeLuca",
        null,
        null,
        5,
        0.273,
        3,
        1,
        1,
        true,
        2,
        2,
        0.9545,
        0.8207,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4311634",
        "Nick Gonzales",
        null,
        null,
        4,
        0.309,
        2,
        1,
        1,
        true,
        4,
        4,
        0.774,
        0.9697,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:42664",
        "Jake Mangum",
        null,
        null,
        4,
        0.301,
        3,
        3,
        3,
        true,
        4,
        4,
        0.774,
        0.952,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4987382",
        "Ceddanne Rafaela",
        null,
        null,
        4,
        0.288,
        2,
        2,
        2,
        true,
        4,
        4,
        0.774,
        0.9167,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:5149072",
        "Kevin McGonigle",
        null,
        null,
        4,
        0.286,
        1,
        1,
        1,
        true,
        5,
        5,
        0.774,
        0.9078,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:40810",
        "Jonathan Aranda",
        null,
        null,
        4,
        0.285,
        1,
        1,
        1,
        true,
        4,
        4,
        0.774,
        0.9003,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:42402",
        "CJ Abrams",
        null,
        null,
        4,
        0.284,
        1,
        1,
        1,
        true,
        3,
        3,
        0.774,
        0.8914,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4414531",
        "Zack Gelof",
        null,
        null,
        4,
        0.28,
        2,
        2,
        2,
        true,
        3,
        3,
        0.774,
        0.8649,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:36181",
        "Mickey Moniak",
        null,
        null,
        4,
        0.271,
        1,
        1,
        1,
        true,
        4,
        4,
        0.774,
        0.8081,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:5007615",
        "Caleb Durbin",
        null,
        null,
        5,
        0.253,
        3,
        1,
        1,
        true,
        4,
        4,
        0.9545,
        0.6187,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4917694",
        "Elly De La Cruz",
        null,
        null,
        4,
        0.268,
        1,
        1,
        1,
        true,
        3,
        3,
        0.774,
        0.7778,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4926296",
        "Jac Caglianone",
        null,
        null,
        4,
        0.268,
        1,
        1,
        1,
        true,
        4,
        4,
        0.774,
        0.7778,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:5137200",
        "Esmerlyn Valdez",
        null,
        null,
        5,
        0.25,
        2,
        2,
        2,
        true,
        4,
        4,
        0.9545,
        0.577,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:33712",
        "Kyle Schwarber",
        null,
        null,
        5,
        0.25,
        2,
        2,
        2,
        true,
        5,
        5,
        0.9545,
        0.577,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:41355",
        "Geraldo Perdomo",
        null,
        null,
        6,
        0.245,
        2,
        1,
        1,
        true,
        4,
        4,
        0.9975,
        0.5189,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4717903",
        "Zac Veen",
        null,
        null,
        3,
        0.333,
        1,
        1,
        1,
        true,
        1,
        1,
        0.5025,
        0.9899,
        "high-high",
        "cluster-2",
        false
      ],
      [
        "mlb:multi_source:player:38904",
        "Bo Bichette",
        null,
        null,
        4,
        0.262,
        1,
        1,
        1,
        true,
        4,
        4,
        0.774,
        0.7008,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4345070",
        "Alec Burleson",
        null,
        null,
        3,
        0.287,
        2,
        1,
        1,
        true,
        4,
        4,
        0.5025,
        0.9129,
        "high-high",
        "cluster-2",
        false
      ],
      [
        "mlb:multi_source:player:32127",
        "Javier Baez",
        null,
        null,
        3,
        0.285,
        1,
        1,
        1,
        true,
        4,
        4,
        0.5025,
        0.9003,
        "high-high",
        "cluster-2",
        false
      ],
      [
        "mlb:multi_source:player:39706",
        "Isaac Paredes",
        null,
        null,
        4,
        0.254,
        0,
        1,
        1,
        true,
        5,
        5,
        0.774,
        0.6275,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4684778",
        "Jordan Walker",
        null,
        null,
        3,
        0.284,
        1,
        1,
        1,
        true,
        4,
        4,
        0.5025,
        0.8914,
        "high-high",
        "cluster-2",
        false
      ],
      [
        "mlb:multi_source:player:30951",
        "Bryce Harper",
        null,
        null,
        4,
        0.253,
        1,
        1,
        1,
        true,
        5,
        5,
        0.774,
        0.6187,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:37232",
        "Donovan Walton",
        null,
        null,
        3,
        0.282,
        1,
        1,
        1,
        true,
        3,
        3,
        0.5025,
        0.8826,
        "high-high",
        "cluster-2",
        false
      ],
      [
        "mlb:multi_source:player:5136929",
        "Chase Meidroth",
        null,
        null,
        3,
        0.279,
        2,
        2,
        2,
        true,
        2,
        2,
        0.5025,
        0.8535,
        "high-high",
        "cluster-2",
        false
      ],
      [
        "mlb:multi_source:player:42933",
        "Jared Triolo",
        null,
        null,
        4,
        0.25,
        3,
        3,
        3,
        true,
        2,
        2,
        0.774,
        0.577,
        "high-high",
        "cluster-3",
        false
      ],
      [
        "mlb:multi_source:player:4917889",
        "Daylen Lile",
        null,
        null,
        4,
        0.249,
        2,
        1,
        1,
        true,
        3,
        3,
        0.774,
        0.5568,
        "high-high",
        "cluster-3",
        false
      ]
    ],
    "rowCount": 36,
    "truncated": true
  }
});
